##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [1]:
import numpy as np

arr =np.array([1,2,3,4,5,6,7,8,9])

arr[[0,4,2]]

array([1, 5, 3])

You can do this fancy indexing in 2D Matrix aswell

In [15]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)

matrix[[0,1,2],[3,0,3]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 4,  5, 12])

##Conditional Selection
Find values based on conditions or replace them.

In [20]:
arr = np.array([1,20,30,90,3,4,50])

arr[arr>10]
np.where(arr>10)


(array([1, 2, 3, 6]),)

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [29]:
array = np.array([42,5,79,9,12,1,7])
np.sort(array)

array([ 1,  5,  7,  9, 12, 42, 79])

In [30]:
np.argsort(array)

array([5, 1, 6, 3, 4, 0, 2])

##Concatenation & Stacking

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concat([a,b])




array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [22]:
A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
B

array([[5, 6],
       [7, 8]])

In [25]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
np.concat((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])