##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [4]:
import numpy as np

a =np.array([1,2,3,4])

b =np.array([5,6,7,8])


print(a+b)
print(a // b)

[ 6  8 10 12]
[0 0 0 0]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [5]:
a =np.array([1,2,3,4])


print(a * 2)

[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [7]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print( arr * 2)

[[ 2  4  6  8]
 [10 12 14 16]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [10]:
b =np.array([5,6,7,8])

print(np.sum(b))
print(np.max(b))
print(np.min(b))
print(np.mean(b))
print(np.std(b))
print(np.var(b))

26
8
5
6.5
1.118033988749895
1.25


You can also do the axis based operations row-Wise and Colum-wise

In [13]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(np.sum(data,axis=1))
print(np.sum(data,axis=0))

[ 6 15 24]
[12 15 18]
