##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [5]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [7]:
arr = np.array([1,2,3,4,5,6])
arr[2]


np.int64(3)

Now lets see the 2D indexing aswell

In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9


In [11]:
print(arr[1])

[4 5 6]


In [12]:
print(arr[0,1])
print(arr[2,2])

2
9


Now we can also do the slicing lets see the **slicing in 1D**

In [13]:
arr = np.array([1,2,3,4,5,6])
arr[:3]

array([1, 2, 3])

1D slicing was really easy now lets see the **slicing in 2D**

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr[0:2, 0:2]
arr[1:3, 1:3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

In [17]:
arr = np.array([1,2,3,4,5,6])
print(arr>3)
print(arr[arr>3])

[False False False  True  True  True]
[4 5 6]


In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr>5)
print(arr[arr>3])

[[False False False]
 [False False  True]
 [ True  True  True]]
[4 5 6 7 8 9]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [25]:
a = np.arange(1,31).reshape(5,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [26]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])