<a href="https://colab.research.google.com/github/amitava-code/numpy/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

Lets create a matrix using list

In [ ]:
a = [[1,2,3],[4,5,6,],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

In [ ]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
arr =  np.zeros([2,2])
arr

array([[0., 0.],
       [0., 0.]])

In [ ]:
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.full([4,4],28)
arr

array([[28, 28, 28, 28],
       [28, 28, 28, 28],
       [28, 28, 28, 28],
       [28, 28, 28, 28]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,10,2)

array([ 0., 10.])

In [ ]:
np.random.rand(2,2)

array([[0.65068204, 0.50304113],
       [0.71843587, 0.86638773]])

In [ ]:
np.random.randn(2,2)

array([[-0.30074088,  0.1187718 ],
       [-0.8626397 , -0.25537312]])

In [ ]:
np.random.randint(1,10,(3,3))

array([[5, 2, 9],
       [1, 9, 9],
       [8, 4, 4]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution